import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { signIn, signOut, useSession } from "next-auth/react";

import { api } from "~/utils/api";
import { ElementType, ReactNode } from "react";
import Nav from "./nav";

interface LayoutProps {
    children: ReactNode;
}

const Layout = ( { children }: LayoutProps ) => {
    const hello = api.example.hello.useQuery({ text: "from tRPC" });
    const { data: session } = useSession()
  
    return (
      <>
        <Head>
          <title>Create T3 App</title>
          <meta name="description" content="Generated by create-t3-app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Nav></Nav>
        <main className="flex min-h-screen flex-col items-center justify-center bg-gray-300">
            {children}
        </main>

      </>
    );
  
  
  };

export default Layout;